version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk1
    ports:
      - "2181:2181"
    hostname: zk1
    networks:
      - kafka-spark
    tty: true

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    links:
      - zookeeper
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "requests-data:6:3"

      KAFKA_LISTENERS: PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092, PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
    networks:
      - kafka-spark
    tty: true

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    depends_on: [ zookeeper ]
    ports:
      - "9093:9093"
    links:
      - zookeeper
    hostname: kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://:19093,PLAINTEXT_HOST://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:19093, PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9093
    networks:
      - kafka-spark
    tty: true

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    depends_on: [ zookeeper ]
    ports:
      - "9094:9094"
    links:
      - zookeeper
    hostname: kafka3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://:19094,PLAINTEXT_HOST://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:19094, PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9094
    networks:
      - kafka-spark
    tty: true

  flume:
    image: myflume
    container_name: flume
    depends_on: [kafka1]
    ports:
      - "40000:40000"
    hostname: flume1
    networks:
      - kafka-spark
    volumes:
      - ./requests:/requests
    tty: true

  redis:
    image: bitnami/redis:5.0
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/data:/data
    networks:
      - kafka-spark


  redis-ui:
    hostname: redis-ui
    container_name: redis-ui
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - kafka-spark

  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    hostname: cassandra
    container_name: cassandra
    ports:
      - '7000:7000'
      - '9042:9042'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - kafka-spark


networks:
  kafka-spark: